###################################################################################################

- name: disable | swapoff
  command: 'swapoff {{ swap_file_absolute_path }}'
  register: swap_swapoff
  changed_when: '{{ swap_swapoff.rc == 0 }}'

###################################################################################################

- name: disable | delete
  file:
    path: '{{ swap_file_absolute_path }}'
    state: absent

###################################################################################################
