###################################################################################################

- name: enable | create
  command: 'fallocate -l 1G {{ swap_file_absolute_path }}'
  args:
    creates: '{{ swap_file_absolute_path }}'

###################################################################################################

- name: enable | permissions
  file:
    path: '{{ swap_file_absolute_path }}'
    mode: 0600

###################################################################################################

- name: enable | mkswap
  command: 'mkswap {{ swap_file_absolute_path }}'

###################################################################################################

- name: enable | swapon
  command: 'swapon {{ swap_file_absolute_path }}'

###################################################################################################
