###################################################################################################

- name: gather facts
  action: setup

###################################################################################################

- name: query
  command: swapon -s
  changed_when: false
  register: swap_query

###################################################################################################

- include: enable.yml
  when:
    - '{{ swap_enable }}'
    - '{{ ansible_swaptotal_mb }} == 0'

###################################################################################################

- include: disable.yml
  when:
    - 'not {{ swap_enable }}'
    - '{{ ansible_swaptotal_mb }} > 0'
    - '{{ swap_query.stdout.find( swap_file_absolute_path ) }} != -1'

###################################################################################################
